name = "pro-discount"
type = "product_discounts"
api_version = "2024-07"

[input.variables]
namespace = "$app:custom-discount"
key = "function-configuration"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/discounts/:functionId/new"
details = "/discounts/:functionId/:id"
