# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "The Pro App"
client_id = "d6ffe7ebb66403fecb8b9cd32737a55a"
application_url = "https://pro-app.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_discounts,write_discounts,read_files,write_files"

[auth]
redirect_urls = [ "https://pro-app.fly.dev/api/auth" ]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://pro-app.fly.dev/proxy"
subpath = "pros"
prefix = "apps"

[pos]
embedded = false
